language: php

php:
  - 5.6
  - 7.0

env:
  - DB=mysql

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer update
  - mysql -e 'create database demo_demotest'
  - php artisan key:generate
  - php artisan migrate --seed
  - php artisan cache:clear
  - chmod -R 777 storage

script:
  - vendor/bin/phpunit